/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthenticatedAccommodationRouteImport } from './routes/_authenticated/accommodation'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDistributionRouteImport } from './routes/_authenticated/distribution'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as DemoLinkCodeRouteImport } from './routes/demo-link.$code'
import { Route as GoCodeRouteImport } from './routes/go.$code'
import { Route as AuthenticatedAccommodationIndexRouteImport } from './routes/_authenticated/accommodation/index'
import { Route as AuthenticatedAccommodationAnalyticsRouteImport } from './routes/_authenticated/accommodation/analytics'
import { Route as AuthenticatedAccommodationBookingsRouteImport } from './routes/_authenticated/accommodation/bookings'
import { Route as AuthenticatedAccommodationDashboardRouteImport } from './routes/_authenticated/accommodation/dashboard'
import { Route as AuthenticatedAccommodationSettingsRouteImport } from './routes/_authenticated/accommodation/settings'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAccommodationsRouteImport } from './routes/_authenticated/admin/accommodations'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'
import { Route as AuthenticatedAdminBookingsRouteImport } from './routes/_authenticated/admin/bookings'
import { Route as AuthenticatedAdminInsightsRouteImport } from './routes/_authenticated/admin/insights'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin/overview'
import { Route as AuthenticatedAdminPartnersRouteImport } from './routes/_authenticated/admin/partners'
import { Route as AuthenticatedAdminReviewRouteImport } from './routes/_authenticated/admin/review'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedDistributionIndexRouteImport } from './routes/_authenticated/distribution/index'
import { Route as AuthenticatedDistributionBookingsRouteImport } from './routes/_authenticated/distribution/bookings'
import { Route as AuthenticatedDistributionDashboardRouteImport } from './routes/_authenticated/distribution/dashboard'
import { Route as AuthenticatedDistributionDiscoverRouteImport } from './routes/_authenticated/distribution/discover'
import { Route as AuthenticatedDistributionLinksRouteImport } from './routes/_authenticated/distribution/links'
import { Route as AuthenticatedDistributionSavedRouteImport } from './routes/_authenticated/distribution/saved'
import { Route as AuthenticatedDistributionSettingsRouteImport } from './routes/_authenticated/distribution/settings'
import { Route as AuthenticatedOnboardingAccommodationRouteImport } from './routes/_authenticated/onboarding/accommodation'
import { Route as AuthenticatedOnboardingDistributionRouteImport } from './routes/_authenticated/onboarding/distribution'
import { Route as AuthenticatedOnboardingRoleRouteImport } from './routes/_authenticated/onboarding/role'
import { Route as AuthenticatedAccommodationAccommodationsIndexRouteImport } from './routes/_authenticated/accommodation/accommodations/index'
import { Route as AuthenticatedAccommodationAccommodationsNewRouteImport } from './routes/_authenticated/accommodation/accommodations/new'
import { Route as AuthenticatedDistributionOpportunitiesIdRouteImport } from './routes/_authenticated/distribution/opportunities.$id'
import { Route as ApiOpportunitiesIdPhotosZipRouteImport } from './routes/api/opportunities.$id.photos-zip'
import { Route as AuthenticatedAccommodationAccommodationsIdIndexRouteImport } from './routes/_authenticated/accommodation/accommodations/$id.index'
import { Route as AuthenticatedAccommodationAccommodationsIdEditRouteImport } from './routes/_authenticated/accommodation/accommodations/$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccommodationRoute =
  AuthenticatedAccommodationRouteImport.update({
    id: '/accommodation',
    path: '/accommodation',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDistributionRoute =
  AuthenticatedDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const DemoLinkCodeRoute = DemoLinkCodeRouteImport.update({
  id: '/demo-link/$code',
  path: '/demo-link/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const GoCodeRoute = GoCodeRouteImport.update({
  id: '/go/$code',
  path: '/go/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccommodationIndexRoute =
  AuthenticatedAccommodationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAccommodationAnalyticsRoute =
  AuthenticatedAccommodationAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAccommodationBookingsRoute =
  AuthenticatedAccommodationBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAccommodationDashboardRoute =
  AuthenticatedAccommodationDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAccommodationSettingsRoute =
  AuthenticatedAccommodationSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAccommodationsRoute =
  AuthenticatedAdminAccommodationsRouteImport.update({
    id: '/accommodations',
    path: '/accommodations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBookingsRoute =
  AuthenticatedAdminBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInsightsRoute =
  AuthenticatedAdminInsightsRouteImport.update({
    id: '/insights',
    path: '/insights',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPartnersRoute =
  AuthenticatedAdminPartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReviewRoute =
  AuthenticatedAdminReviewRouteImport.update({
    id: '/review',
    path: '/review',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedDistributionIndexRoute =
  AuthenticatedDistributionIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDistributionBookingsRoute =
  AuthenticatedDistributionBookingsRouteImport.update({
    id: '/bookings',
    path: '/bookings',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDistributionDashboardRoute =
  AuthenticatedDistributionDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDistributionDiscoverRoute =
  AuthenticatedDistributionDiscoverRouteImport.update({
    id: '/discover',
    path: '/discover',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDistributionLinksRoute =
  AuthenticatedDistributionLinksRouteImport.update({
    id: '/links',
    path: '/links',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDistributionSavedRoute =
  AuthenticatedDistributionSavedRouteImport.update({
    id: '/saved',
    path: '/saved',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedDistributionSettingsRoute =
  AuthenticatedDistributionSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const AuthenticatedOnboardingAccommodationRoute =
  AuthenticatedOnboardingAccommodationRouteImport.update({
    id: '/accommodation',
    path: '/accommodation',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingDistributionRoute =
  AuthenticatedOnboardingDistributionRouteImport.update({
    id: '/distribution',
    path: '/distribution',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedOnboardingRoleRoute =
  AuthenticatedOnboardingRoleRouteImport.update({
    id: '/role',
    path: '/role',
    getParentRoute: () => AuthenticatedOnboardingRoute,
  } as any)
const AuthenticatedAccommodationAccommodationsIndexRoute =
  AuthenticatedAccommodationAccommodationsIndexRouteImport.update({
    id: '/accommodations/',
    path: '/accommodations/',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAccommodationAccommodationsNewRoute =
  AuthenticatedAccommodationAccommodationsNewRouteImport.update({
    id: '/accommodations/new',
    path: '/accommodations/new',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedDistributionOpportunitiesIdRoute =
  AuthenticatedDistributionOpportunitiesIdRouteImport.update({
    id: '/opportunities/$id',
    path: '/opportunities/$id',
    getParentRoute: () => AuthenticatedDistributionRoute,
  } as any)
const ApiOpportunitiesIdPhotosZipRoute =
  ApiOpportunitiesIdPhotosZipRouteImport.update({
    id: '/api/opportunities/$id/photos-zip',
    path: '/api/opportunities/$id/photos-zip',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAccommodationAccommodationsIdIndexRoute =
  AuthenticatedAccommodationAccommodationsIdIndexRouteImport.update({
    id: '/accommodations/$id/',
    path: '/accommodations/$id/',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)
const AuthenticatedAccommodationAccommodationsIdEditRoute =
  AuthenticatedAccommodationAccommodationsIdEditRouteImport.update({
    id: '/accommodations/$id/edit',
    path: '/accommodations/$id/edit',
    getParentRoute: () => AuthenticatedAccommodationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/accommodation': typeof AuthenticatedAccommodationRouteWithChildren
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/demo-link/$code': typeof DemoLinkCodeRoute
  '/go/$code': typeof GoCodeRoute
  '/accommodation/analytics': typeof AuthenticatedAccommodationAnalyticsRoute
  '/accommodation/bookings': typeof AuthenticatedAccommodationBookingsRoute
  '/accommodation/dashboard': typeof AuthenticatedAccommodationDashboardRoute
  '/accommodation/settings': typeof AuthenticatedAccommodationSettingsRoute
  '/admin/accommodations': typeof AuthenticatedAdminAccommodationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/distribution/bookings': typeof AuthenticatedDistributionBookingsRoute
  '/distribution/dashboard': typeof AuthenticatedDistributionDashboardRoute
  '/distribution/discover': typeof AuthenticatedDistributionDiscoverRoute
  '/distribution/links': typeof AuthenticatedDistributionLinksRoute
  '/distribution/saved': typeof AuthenticatedDistributionSavedRoute
  '/distribution/settings': typeof AuthenticatedDistributionSettingsRoute
  '/onboarding/accommodation': typeof AuthenticatedOnboardingAccommodationRoute
  '/onboarding/distribution': typeof AuthenticatedOnboardingDistributionRoute
  '/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/accommodation/': typeof AuthenticatedAccommodationIndexRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/distribution/': typeof AuthenticatedDistributionIndexRoute
  '/accommodation/accommodations/new': typeof AuthenticatedAccommodationAccommodationsNewRoute
  '/distribution/opportunities/$id': typeof AuthenticatedDistributionOpportunitiesIdRoute
  '/api/opportunities/$id/photos-zip': typeof ApiOpportunitiesIdPhotosZipRoute
  '/accommodation/accommodations/': typeof AuthenticatedAccommodationAccommodationsIndexRoute
  '/accommodation/accommodations/$id/edit': typeof AuthenticatedAccommodationAccommodationsIdEditRoute
  '/accommodation/accommodations/$id/': typeof AuthenticatedAccommodationAccommodationsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/demo-link/$code': typeof DemoLinkCodeRoute
  '/go/$code': typeof GoCodeRoute
  '/accommodation/analytics': typeof AuthenticatedAccommodationAnalyticsRoute
  '/accommodation/bookings': typeof AuthenticatedAccommodationBookingsRoute
  '/accommodation/dashboard': typeof AuthenticatedAccommodationDashboardRoute
  '/accommodation/settings': typeof AuthenticatedAccommodationSettingsRoute
  '/admin/accommodations': typeof AuthenticatedAdminAccommodationsRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/admin/review': typeof AuthenticatedAdminReviewRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/distribution/bookings': typeof AuthenticatedDistributionBookingsRoute
  '/distribution/dashboard': typeof AuthenticatedDistributionDashboardRoute
  '/distribution/discover': typeof AuthenticatedDistributionDiscoverRoute
  '/distribution/links': typeof AuthenticatedDistributionLinksRoute
  '/distribution/saved': typeof AuthenticatedDistributionSavedRoute
  '/distribution/settings': typeof AuthenticatedDistributionSettingsRoute
  '/onboarding/accommodation': typeof AuthenticatedOnboardingAccommodationRoute
  '/onboarding/distribution': typeof AuthenticatedOnboardingDistributionRoute
  '/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/accommodation': typeof AuthenticatedAccommodationIndexRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/distribution': typeof AuthenticatedDistributionIndexRoute
  '/accommodation/accommodations/new': typeof AuthenticatedAccommodationAccommodationsNewRoute
  '/distribution/opportunities/$id': typeof AuthenticatedDistributionOpportunitiesIdRoute
  '/api/opportunities/$id/photos-zip': typeof ApiOpportunitiesIdPhotosZipRoute
  '/accommodation/accommodations': typeof AuthenticatedAccommodationAccommodationsIndexRoute
  '/accommodation/accommodations/$id/edit': typeof AuthenticatedAccommodationAccommodationsIdEditRoute
  '/accommodation/accommodations/$id': typeof AuthenticatedAccommodationAccommodationsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/terms': typeof TermsRoute
  '/_authenticated/accommodation': typeof AuthenticatedAccommodationRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/distribution': typeof AuthenticatedDistributionRouteWithChildren
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRouteWithChildren
  '/demo-link/$code': typeof DemoLinkCodeRoute
  '/go/$code': typeof GoCodeRoute
  '/_authenticated/accommodation/analytics': typeof AuthenticatedAccommodationAnalyticsRoute
  '/_authenticated/accommodation/bookings': typeof AuthenticatedAccommodationBookingsRoute
  '/_authenticated/accommodation/dashboard': typeof AuthenticatedAccommodationDashboardRoute
  '/_authenticated/accommodation/settings': typeof AuthenticatedAccommodationSettingsRoute
  '/_authenticated/admin/accommodations': typeof AuthenticatedAdminAccommodationsRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/bookings': typeof AuthenticatedAdminBookingsRoute
  '/_authenticated/admin/insights': typeof AuthenticatedAdminInsightsRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/partners': typeof AuthenticatedAdminPartnersRoute
  '/_authenticated/admin/review': typeof AuthenticatedAdminReviewRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/distribution/bookings': typeof AuthenticatedDistributionBookingsRoute
  '/_authenticated/distribution/dashboard': typeof AuthenticatedDistributionDashboardRoute
  '/_authenticated/distribution/discover': typeof AuthenticatedDistributionDiscoverRoute
  '/_authenticated/distribution/links': typeof AuthenticatedDistributionLinksRoute
  '/_authenticated/distribution/saved': typeof AuthenticatedDistributionSavedRoute
  '/_authenticated/distribution/settings': typeof AuthenticatedDistributionSettingsRoute
  '/_authenticated/onboarding/accommodation': typeof AuthenticatedOnboardingAccommodationRoute
  '/_authenticated/onboarding/distribution': typeof AuthenticatedOnboardingDistributionRoute
  '/_authenticated/onboarding/role': typeof AuthenticatedOnboardingRoleRoute
  '/_authenticated/accommodation/': typeof AuthenticatedAccommodationIndexRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/distribution/': typeof AuthenticatedDistributionIndexRoute
  '/_authenticated/accommodation/accommodations/new': typeof AuthenticatedAccommodationAccommodationsNewRoute
  '/_authenticated/distribution/opportunities/$id': typeof AuthenticatedDistributionOpportunitiesIdRoute
  '/api/opportunities/$id/photos-zip': typeof ApiOpportunitiesIdPhotosZipRoute
  '/_authenticated/accommodation/accommodations/': typeof AuthenticatedAccommodationAccommodationsIndexRoute
  '/_authenticated/accommodation/accommodations/$id/edit': typeof AuthenticatedAccommodationAccommodationsIdEditRoute
  '/_authenticated/accommodation/accommodations/$id/': typeof AuthenticatedAccommodationAccommodationsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/terms'
    | '/accommodation'
    | '/admin'
    | '/dashboard'
    | '/distribution'
    | '/onboarding'
    | '/demo-link/$code'
    | '/go/$code'
    | '/accommodation/analytics'
    | '/accommodation/bookings'
    | '/accommodation/dashboard'
    | '/accommodation/settings'
    | '/admin/accommodations'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/insights'
    | '/admin/overview'
    | '/admin/partners'
    | '/admin/review'
    | '/admin/settings'
    | '/admin/users'
    | '/distribution/bookings'
    | '/distribution/dashboard'
    | '/distribution/discover'
    | '/distribution/links'
    | '/distribution/saved'
    | '/distribution/settings'
    | '/onboarding/accommodation'
    | '/onboarding/distribution'
    | '/onboarding/role'
    | '/accommodation/'
    | '/admin/'
    | '/distribution/'
    | '/accommodation/accommodations/new'
    | '/distribution/opportunities/$id'
    | '/api/opportunities/$id/photos-zip'
    | '/accommodation/accommodations/'
    | '/accommodation/accommodations/$id/edit'
    | '/accommodation/accommodations/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/terms'
    | '/dashboard'
    | '/onboarding'
    | '/demo-link/$code'
    | '/go/$code'
    | '/accommodation/analytics'
    | '/accommodation/bookings'
    | '/accommodation/dashboard'
    | '/accommodation/settings'
    | '/admin/accommodations'
    | '/admin/audit'
    | '/admin/bookings'
    | '/admin/insights'
    | '/admin/overview'
    | '/admin/partners'
    | '/admin/review'
    | '/admin/settings'
    | '/admin/users'
    | '/distribution/bookings'
    | '/distribution/dashboard'
    | '/distribution/discover'
    | '/distribution/links'
    | '/distribution/saved'
    | '/distribution/settings'
    | '/onboarding/accommodation'
    | '/onboarding/distribution'
    | '/onboarding/role'
    | '/accommodation'
    | '/admin'
    | '/distribution'
    | '/accommodation/accommodations/new'
    | '/distribution/opportunities/$id'
    | '/api/opportunities/$id/photos-zip'
    | '/accommodation/accommodations'
    | '/accommodation/accommodations/$id/edit'
    | '/accommodation/accommodations/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/terms'
    | '/_authenticated/accommodation'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/distribution'
    | '/_authenticated/onboarding'
    | '/demo-link/$code'
    | '/go/$code'
    | '/_authenticated/accommodation/analytics'
    | '/_authenticated/accommodation/bookings'
    | '/_authenticated/accommodation/dashboard'
    | '/_authenticated/accommodation/settings'
    | '/_authenticated/admin/accommodations'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/bookings'
    | '/_authenticated/admin/insights'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/partners'
    | '/_authenticated/admin/review'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/users'
    | '/_authenticated/distribution/bookings'
    | '/_authenticated/distribution/dashboard'
    | '/_authenticated/distribution/discover'
    | '/_authenticated/distribution/links'
    | '/_authenticated/distribution/saved'
    | '/_authenticated/distribution/settings'
    | '/_authenticated/onboarding/accommodation'
    | '/_authenticated/onboarding/distribution'
    | '/_authenticated/onboarding/role'
    | '/_authenticated/accommodation/'
    | '/_authenticated/admin/'
    | '/_authenticated/distribution/'
    | '/_authenticated/accommodation/accommodations/new'
    | '/_authenticated/distribution/opportunities/$id'
    | '/api/opportunities/$id/photos-zip'
    | '/_authenticated/accommodation/accommodations/'
    | '/_authenticated/accommodation/accommodations/$id/edit'
    | '/_authenticated/accommodation/accommodations/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermsRoute: typeof TermsRoute
  DemoLinkCodeRoute: typeof DemoLinkCodeRoute
  GoCodeRoute: typeof GoCodeRoute
  ApiOpportunitiesIdPhotosZipRoute: typeof ApiOpportunitiesIdPhotosZipRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accommodation': {
      id: '/_authenticated/accommodation'
      path: '/accommodation'
      fullPath: '/accommodation'
      preLoaderRoute: typeof AuthenticatedAccommodationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/distribution': {
      id: '/_authenticated/distribution'
      path: '/distribution'
      fullPath: '/distribution'
      preLoaderRoute: typeof AuthenticatedDistributionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/demo-link/$code': {
      id: '/demo-link/$code'
      path: '/demo-link/$code'
      fullPath: '/demo-link/$code'
      preLoaderRoute: typeof DemoLinkCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/go/$code': {
      id: '/go/$code'
      path: '/go/$code'
      fullPath: '/go/$code'
      preLoaderRoute: typeof GoCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accommodation/': {
      id: '/_authenticated/accommodation/'
      path: '/'
      fullPath: '/accommodation/'
      preLoaderRoute: typeof AuthenticatedAccommodationIndexRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/accommodation/analytics': {
      id: '/_authenticated/accommodation/analytics'
      path: '/analytics'
      fullPath: '/accommodation/analytics'
      preLoaderRoute: typeof AuthenticatedAccommodationAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/accommodation/bookings': {
      id: '/_authenticated/accommodation/bookings'
      path: '/bookings'
      fullPath: '/accommodation/bookings'
      preLoaderRoute: typeof AuthenticatedAccommodationBookingsRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/accommodation/dashboard': {
      id: '/_authenticated/accommodation/dashboard'
      path: '/dashboard'
      fullPath: '/accommodation/dashboard'
      preLoaderRoute: typeof AuthenticatedAccommodationDashboardRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/accommodation/settings': {
      id: '/_authenticated/accommodation/settings'
      path: '/settings'
      fullPath: '/accommodation/settings'
      preLoaderRoute: typeof AuthenticatedAccommodationSettingsRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/accommodations': {
      id: '/_authenticated/admin/accommodations'
      path: '/accommodations'
      fullPath: '/admin/accommodations'
      preLoaderRoute: typeof AuthenticatedAdminAccommodationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/bookings': {
      id: '/_authenticated/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AuthenticatedAdminBookingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/insights': {
      id: '/_authenticated/admin/insights'
      path: '/insights'
      fullPath: '/admin/insights'
      preLoaderRoute: typeof AuthenticatedAdminInsightsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/partners': {
      id: '/_authenticated/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AuthenticatedAdminPartnersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/review': {
      id: '/_authenticated/admin/review'
      path: '/review'
      fullPath: '/admin/review'
      preLoaderRoute: typeof AuthenticatedAdminReviewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/distribution/': {
      id: '/_authenticated/distribution/'
      path: '/'
      fullPath: '/distribution/'
      preLoaderRoute: typeof AuthenticatedDistributionIndexRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/distribution/bookings': {
      id: '/_authenticated/distribution/bookings'
      path: '/bookings'
      fullPath: '/distribution/bookings'
      preLoaderRoute: typeof AuthenticatedDistributionBookingsRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/distribution/dashboard': {
      id: '/_authenticated/distribution/dashboard'
      path: '/dashboard'
      fullPath: '/distribution/dashboard'
      preLoaderRoute: typeof AuthenticatedDistributionDashboardRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/distribution/discover': {
      id: '/_authenticated/distribution/discover'
      path: '/discover'
      fullPath: '/distribution/discover'
      preLoaderRoute: typeof AuthenticatedDistributionDiscoverRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/distribution/links': {
      id: '/_authenticated/distribution/links'
      path: '/links'
      fullPath: '/distribution/links'
      preLoaderRoute: typeof AuthenticatedDistributionLinksRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/distribution/saved': {
      id: '/_authenticated/distribution/saved'
      path: '/saved'
      fullPath: '/distribution/saved'
      preLoaderRoute: typeof AuthenticatedDistributionSavedRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/distribution/settings': {
      id: '/_authenticated/distribution/settings'
      path: '/settings'
      fullPath: '/distribution/settings'
      preLoaderRoute: typeof AuthenticatedDistributionSettingsRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/_authenticated/onboarding/accommodation': {
      id: '/_authenticated/onboarding/accommodation'
      path: '/accommodation'
      fullPath: '/onboarding/accommodation'
      preLoaderRoute: typeof AuthenticatedOnboardingAccommodationRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/distribution': {
      id: '/_authenticated/onboarding/distribution'
      path: '/distribution'
      fullPath: '/onboarding/distribution'
      preLoaderRoute: typeof AuthenticatedOnboardingDistributionRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/onboarding/role': {
      id: '/_authenticated/onboarding/role'
      path: '/role'
      fullPath: '/onboarding/role'
      preLoaderRoute: typeof AuthenticatedOnboardingRoleRouteImport
      parentRoute: typeof AuthenticatedOnboardingRoute
    }
    '/_authenticated/accommodation/accommodations/': {
      id: '/_authenticated/accommodation/accommodations/'
      path: '/accommodations'
      fullPath: '/accommodation/accommodations/'
      preLoaderRoute: typeof AuthenticatedAccommodationAccommodationsIndexRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/accommodation/accommodations/new': {
      id: '/_authenticated/accommodation/accommodations/new'
      path: '/accommodations/new'
      fullPath: '/accommodation/accommodations/new'
      preLoaderRoute: typeof AuthenticatedAccommodationAccommodationsNewRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/distribution/opportunities/$id': {
      id: '/_authenticated/distribution/opportunities/$id'
      path: '/opportunities/$id'
      fullPath: '/distribution/opportunities/$id'
      preLoaderRoute: typeof AuthenticatedDistributionOpportunitiesIdRouteImport
      parentRoute: typeof AuthenticatedDistributionRoute
    }
    '/api/opportunities/$id/photos-zip': {
      id: '/api/opportunities/$id/photos-zip'
      path: '/api/opportunities/$id/photos-zip'
      fullPath: '/api/opportunities/$id/photos-zip'
      preLoaderRoute: typeof ApiOpportunitiesIdPhotosZipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accommodation/accommodations/$id/': {
      id: '/_authenticated/accommodation/accommodations/$id/'
      path: '/accommodations/$id'
      fullPath: '/accommodation/accommodations/$id/'
      preLoaderRoute: typeof AuthenticatedAccommodationAccommodationsIdIndexRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
    '/_authenticated/accommodation/accommodations/$id/edit': {
      id: '/_authenticated/accommodation/accommodations/$id/edit'
      path: '/accommodations/$id/edit'
      fullPath: '/accommodation/accommodations/$id/edit'
      preLoaderRoute: typeof AuthenticatedAccommodationAccommodationsIdEditRouteImport
      parentRoute: typeof AuthenticatedAccommodationRoute
    }
  }
}

interface AuthenticatedAccommodationRouteChildren {
  AuthenticatedAccommodationAnalyticsRoute: typeof AuthenticatedAccommodationAnalyticsRoute
  AuthenticatedAccommodationBookingsRoute: typeof AuthenticatedAccommodationBookingsRoute
  AuthenticatedAccommodationDashboardRoute: typeof AuthenticatedAccommodationDashboardRoute
  AuthenticatedAccommodationSettingsRoute: typeof AuthenticatedAccommodationSettingsRoute
  AuthenticatedAccommodationIndexRoute: typeof AuthenticatedAccommodationIndexRoute
  AuthenticatedAccommodationAccommodationsNewRoute: typeof AuthenticatedAccommodationAccommodationsNewRoute
  AuthenticatedAccommodationAccommodationsIndexRoute: typeof AuthenticatedAccommodationAccommodationsIndexRoute
  AuthenticatedAccommodationAccommodationsIdEditRoute: typeof AuthenticatedAccommodationAccommodationsIdEditRoute
  AuthenticatedAccommodationAccommodationsIdIndexRoute: typeof AuthenticatedAccommodationAccommodationsIdIndexRoute
}

const AuthenticatedAccommodationRouteChildren: AuthenticatedAccommodationRouteChildren =
  {
    AuthenticatedAccommodationAnalyticsRoute:
      AuthenticatedAccommodationAnalyticsRoute,
    AuthenticatedAccommodationBookingsRoute:
      AuthenticatedAccommodationBookingsRoute,
    AuthenticatedAccommodationDashboardRoute:
      AuthenticatedAccommodationDashboardRoute,
    AuthenticatedAccommodationSettingsRoute:
      AuthenticatedAccommodationSettingsRoute,
    AuthenticatedAccommodationIndexRoute: AuthenticatedAccommodationIndexRoute,
    AuthenticatedAccommodationAccommodationsNewRoute:
      AuthenticatedAccommodationAccommodationsNewRoute,
    AuthenticatedAccommodationAccommodationsIndexRoute:
      AuthenticatedAccommodationAccommodationsIndexRoute,
    AuthenticatedAccommodationAccommodationsIdEditRoute:
      AuthenticatedAccommodationAccommodationsIdEditRoute,
    AuthenticatedAccommodationAccommodationsIdIndexRoute:
      AuthenticatedAccommodationAccommodationsIdIndexRoute,
  }

const AuthenticatedAccommodationRouteWithChildren =
  AuthenticatedAccommodationRoute._addFileChildren(
    AuthenticatedAccommodationRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAccommodationsRoute: typeof AuthenticatedAdminAccommodationsRoute
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminBookingsRoute: typeof AuthenticatedAdminBookingsRoute
  AuthenticatedAdminInsightsRoute: typeof AuthenticatedAdminInsightsRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminPartnersRoute: typeof AuthenticatedAdminPartnersRoute
  AuthenticatedAdminReviewRoute: typeof AuthenticatedAdminReviewRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAccommodationsRoute: AuthenticatedAdminAccommodationsRoute,
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminBookingsRoute: AuthenticatedAdminBookingsRoute,
  AuthenticatedAdminInsightsRoute: AuthenticatedAdminInsightsRoute,
  AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
  AuthenticatedAdminPartnersRoute: AuthenticatedAdminPartnersRoute,
  AuthenticatedAdminReviewRoute: AuthenticatedAdminReviewRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedDistributionRouteChildren {
  AuthenticatedDistributionBookingsRoute: typeof AuthenticatedDistributionBookingsRoute
  AuthenticatedDistributionDashboardRoute: typeof AuthenticatedDistributionDashboardRoute
  AuthenticatedDistributionDiscoverRoute: typeof AuthenticatedDistributionDiscoverRoute
  AuthenticatedDistributionLinksRoute: typeof AuthenticatedDistributionLinksRoute
  AuthenticatedDistributionSavedRoute: typeof AuthenticatedDistributionSavedRoute
  AuthenticatedDistributionSettingsRoute: typeof AuthenticatedDistributionSettingsRoute
  AuthenticatedDistributionIndexRoute: typeof AuthenticatedDistributionIndexRoute
  AuthenticatedDistributionOpportunitiesIdRoute: typeof AuthenticatedDistributionOpportunitiesIdRoute
}

const AuthenticatedDistributionRouteChildren: AuthenticatedDistributionRouteChildren =
  {
    AuthenticatedDistributionBookingsRoute:
      AuthenticatedDistributionBookingsRoute,
    AuthenticatedDistributionDashboardRoute:
      AuthenticatedDistributionDashboardRoute,
    AuthenticatedDistributionDiscoverRoute:
      AuthenticatedDistributionDiscoverRoute,
    AuthenticatedDistributionLinksRoute: AuthenticatedDistributionLinksRoute,
    AuthenticatedDistributionSavedRoute: AuthenticatedDistributionSavedRoute,
    AuthenticatedDistributionSettingsRoute:
      AuthenticatedDistributionSettingsRoute,
    AuthenticatedDistributionIndexRoute: AuthenticatedDistributionIndexRoute,
    AuthenticatedDistributionOpportunitiesIdRoute:
      AuthenticatedDistributionOpportunitiesIdRoute,
  }

const AuthenticatedDistributionRouteWithChildren =
  AuthenticatedDistributionRoute._addFileChildren(
    AuthenticatedDistributionRouteChildren,
  )

interface AuthenticatedOnboardingRouteChildren {
  AuthenticatedOnboardingAccommodationRoute: typeof AuthenticatedOnboardingAccommodationRoute
  AuthenticatedOnboardingDistributionRoute: typeof AuthenticatedOnboardingDistributionRoute
  AuthenticatedOnboardingRoleRoute: typeof AuthenticatedOnboardingRoleRoute
}

const AuthenticatedOnboardingRouteChildren: AuthenticatedOnboardingRouteChildren =
  {
    AuthenticatedOnboardingAccommodationRoute:
      AuthenticatedOnboardingAccommodationRoute,
    AuthenticatedOnboardingDistributionRoute:
      AuthenticatedOnboardingDistributionRoute,
    AuthenticatedOnboardingRoleRoute: AuthenticatedOnboardingRoleRoute,
  }

const AuthenticatedOnboardingRouteWithChildren =
  AuthenticatedOnboardingRoute._addFileChildren(
    AuthenticatedOnboardingRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccommodationRoute: typeof AuthenticatedAccommodationRouteWithChildren
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDistributionRoute: typeof AuthenticatedDistributionRouteWithChildren
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccommodationRoute: AuthenticatedAccommodationRouteWithChildren,
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDistributionRoute: AuthenticatedDistributionRouteWithChildren,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermsRoute: TermsRoute,
  DemoLinkCodeRoute: DemoLinkCodeRoute,
  GoCodeRoute: GoCodeRoute,
  ApiOpportunitiesIdPhotosZipRoute: ApiOpportunitiesIdPhotosZipRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
